approvedGitRepositories:
  - "**"

enableScripts: true

nodeLinker: node-modules

npmMinimalAgeGate: 14d

npmPreapprovedPackages:
  - "@side/*"
  - "@google/*"
  - "google-*"
  - "@datadog/*"
  - "next"
  - "react"
  - "react-dom"
  - "@yarnpkg/cli"

yarnPath: .yarn/releases/yarn-4.14.1.cjs
