name: Verify

on:
  pull_request:
    branches:
      - main

concurrency:
  group: verify-${{ github.head_ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: 20.x

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'

      - name: Configure package manager
        run: |
          echo Configuring NPM_TOKEN globally for .npmrc
          npm config set '//registry.npmjs.org/:_authToken' ${{ secrets.NPM_READ_TOKEN }}
          yarn config set npmAuthToken ${{ secrets.NPM_READ_TOKEN }}
          npm whoami

      - name: Install dependencies
        run: yarn install --frozen-lockfile

        # See https://docs.renovatebot.com/config-validation/
      - name: Validate renovate config
        run: |
          for filename in $GITHUB_WORKSPACE/*.json; do
            if [[ "$filename" != *"package.json" ]]; then
              echo "Validating $filename"
              npx --yes --package renovate -- renovate-config-validator $filename
            fi
          done

      - name: Verify formatting
        run: yarn lint && yarn format:check
