name: Verify

on:
  pull_request:
    branches:
      - main

concurrency:
  group: verify-${{ github.head_ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: 20.x

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'

      - name: Configure package manager
        run: |
          echo Configuring NPM_TOKEN globally for .npmrc
          npm config set '//registry.npmjs.org/:_authToken' ${{ secrets.NPM_READ_TOKEN }}
          yarn config set npmAuthToken ${{ secrets.NPM_READ_TOKEN }}
          npm whoami

      - name: Install dependencies
        run: yarn install --frozen-lockfile

        # See https://docs.renovatebot.com/config-validation/
      - name: Validate renovate config
        run: npx --yes --package renovate -- renovate-config-validator

      - name: Verify formatting
        run: yarn lint && yarn format
